### ISSUE TITLE
Add Guide for CDKTF + Github Actions

### ISSUE THREAD

**Issue by amcdnl** [hashicorp/terraform-cdk#1735]
## Issue
The terraform CLI has docs for Github Action deploys but the CDKTF is not as clear. It would be nice to have a guide for how to integrate the CDKTF and Github Actions explicitly.

Here is my config I ended up with that might help others:

```
name: deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
      terraform_version: 1.1.7

    steps:
    - uses: actions/checkout@v2
   
    - uses: actions/setup-node@v2
      with:
        node-version: "16"
        cache: "yarn"

    - name: Install
      run: yarn install --frozen-lockfile --non-interactive

    - name: Build App
      run: yarn build:prod

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
        terraform_version: 1.1.7
        terraform_wrapper: false

    - name: Terraform Synth
      run: |
        yarn terraform:get
        yarn terraform:synth

    - name: Terraform Init
      run: terraform init
      working-directory: ./.terraform/cdktf.out/stacks/myapp

    - name: Terraform Validate
      run: terraform validate -no-color
      working-directory: ./.terraform/cdktf.out/stacksmyapp

    - name: Terraform Plan
      run: terraform plan -no-color
      working-directory: ./.terraform/cdktf.out/stacks/myapp

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      working-directory: ./.terraform/cdktf.out/stacks/myapp

    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: myapp.app
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: 'build'
```
