### ISSUE TITLE
Example for Unit Tests

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#210]
As @frezbo pointed out in https://github.com/hashicorp/terraform-cdk/issues/47#issuecomment-660700734

> I would also like to see examples around writing Unit Tests. That seems to be missing.

It would be good to have an example and perhaps docs for unit testing. 

To get started, snapshot tests are likely sufficient. We sort of do this here already https://github.com/hashicorp/terraform-cdk/blob/56c58c95737e6de9f797502d2863177d7a11fbe7/packages/cdktf/test/resource.test.ts Will need a bit of polishing, but is a good starting point.

Later on, dedicated matchers could be built to make fine granular testing easier.

**Comment by stefanfreitag** [comment]
Not only some input on writing unit tests would be appreciated, but also some guidance on setting up CI jobs for test execution.

Starting from a fresh typescript project I added jest and a snapshot test. Testing locally is not an issue at all. It took me a bit to get the test executed on an external CI tool (CircleCI). But I am not sure if there are better approaches compared to the one I currently have: e.g. downloading `terraform` every time seems inefficient.

To understand better how my tests are executed I added the `yml` configuration of the CircleCI job.
If I got it right I would need aside of `terraform` also the `cdktf-cli`. It will generate the `.gen` folder by running `cdktf get`.

```
 version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Download Terraform
          command: curl -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip
      - run:
          name: Install Terraform
          command: sudo unzip /tmp/terraform.zip -d /usr/bin/
      - node/with-cache:
          steps:
            - run: sudo npm install -g cdktf-cli
            - run: npm install
            - run: cdktf get
            - run: npm test

workflows:
    build-and-test:
      jobs:
        - build-and-test

```
