### ISSUE TITLE
Add YAML support

### ISSUE THREAD

**Issue by JayDoubleu** [hashicorp/terraform-cdk#236]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I've been using terraform funtions (json and yaml decode/encode)
To convert terraform json <> terraform yaml.

Would it be possible to have similar terraform validated yaml output from synth ? 

```json
{
  "//": {
    "metadata": {
      "version": "0.0.12",
      "stackName": "python-azure"
    }
  },
  "terraform": {
    "required_providers": {
      "azurerm": "~> 2.0"
    }
  },
  "provider": {
    "azurerm": [
      {
        "subscription_id": "<>",
        "tenant_id": "<>",
        "features": [
          {}
        ]
      }
    ]
  },
  "resource": {
    "azurerm_resource_group": {
      "pythonazure_testrg_4EE2DCD8": {
        "location": "northeurope",
        "name": "test",
        "//": {
          "metadata": {
            "path": "python-azure/testrg",
            "uniqueId": "pythonazure_testrg_4EE2DCD8",
            "stackTrace": []
          }
        }
      }
    }
  }
}
```

```yaml
"//":
  "metadata":
    "stackName": "python-azure"
    "version": "0.0.12"
"provider":
  "azurerm":
  - "features":
    - {}
    "subscription_id": "<>"
    "tenant_id": "<>"
"resource":
  "azurerm_resource_group":
    "pythonazure_testrg_4EE2DCD8":
      "//":
        "metadata":
          "path": "python-azure/testrg"
          "stackTrace": []
          "uniqueId": "pythonazure_testrg_4EE2DCD8"
      "location": "northeurope"
      "name": "test"
"terraform":
  "required_providers":
    "azurerm": "~> 2.0"

```

**Comment by skorfmann** [comment]
Is YAML supported as input for Terraform?? Besides, what would be the use-case for you?

**Comment by JayDoubleu** [comment]
Terraform itself is ignoring the `.tf.yml` files however there are some tricks within terraform to convert from JSON format into YAML for better human readability , and then back to `.tf.json`

```shell
#!/bin/bash
export TF_IN_AUTOMATION="yup"
rm -rf tfCode_generate*
rm -rf .terraform
rm -rf terraform.tfstate*
rm -rf yaml json json_
mkdir -p yaml json json_
# cdktf generated tf.json
cat <<EOF > json/tfCode.tf.json.generated
{
  "//": {
    "metadata": {
      "version": "0.0.12",
      "stackName": "python-azure"
    }
  },
  "terraform": {
    "required_providers": {
      "azurerm": "~> 2.0"
    }
  },
  "provider": {
    "azurerm": [
      {
        "subscription_id": "subscription_guid",
        "tenant_id": "tenant_guid",
        "features": [
          {}
        ]
      }
    ]
  },
  "resource": {
    "azurerm_resource_group": {
      "pythonazure_testrg_4EE2DCD8": {
        "location": "northeurope",
        "name": "test"
      }
    }
  }
}
EOF
# sample code using terraform to convert to YAML for user edits.
cat <<'EOF' > tfCode_generate_yaml.tf
locals {
  environment = "dev"
  content = jsondecode(file("json/tfCode.tf.json.generated"))
  content_yaml = yamlencode(local.content)
}
resource "local_file" "tfCode_yaml" {
  content  = local.content_yaml
  filename = "yaml/tfCode.tf.yaml"
}
output "decoded" { value = local.content }
output "decoded_yaml" { value = local.content_yaml }
EOF

#generate terraform valid YAML file
terraform init
terraform apply -auto-approve


# user edits the YAML
terraform state rm local_file.tfCode_yaml
rm -rf .terraform
mv tfCode_generate_yaml.tf tfCode_generate_yaml.tf.nope

cat <<'EOF' > tfCode_generate_json.tf
resource "local_file" "tfCode_json" {
  content = jsonencode(yamldecode(file("${path.module}/yaml/tfCode.tf.yaml")))
  filename = "${path.module}/json_/tfCode.tf.json"
}
output "decoded_json" { value = local_file.tfCode_json.content }
EOF
#
terraform init
terraform apply -auto-approve
# display re-generated JSON file
python -m json.tool json_/tfCode.tf.json

# run re-generated terraform
cd json_ && terraform init && terraform plan
```

```shell
Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "local" (hashicorp/local) 1.4.0...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.local: version = "~> 1.4"

Terraform has been successfully initialized!
local_file.tfCode_yaml: Creating...
local_file.tfCode_yaml: Creation complete after 0s [id=e681fdbf97352ef1d9a6f512be0a2f12a53e230f]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

decoded = {
  "//" = {
    "metadata" = {
      "stackName" = "python-azure"
      "version" = "0.0.12"
    }
  }
  "provider" = {
    "azurerm" = [
      {
        "features" = [
          {},
        ]
        "subscription_id" = "subscription_guid"
        "tenant_id" = "tenant_guid"
      },
    ]
  }
  "resource" = {
    "azurerm_resource_group" = {
      "pythonazure_testrg_4EE2DCD8" = {
        "location" = "northeurope"
        "name" = "test"
      }
    }
  }
  "terraform" = {
    "required_providers" = {
      "azurerm" = "~> 2.0"
    }
  }
}
decoded_yaml = "//":
  "metadata":
    "stackName": "python-azure"
    "version": "0.0.12"
"provider":
  "azurerm":
  - "features":
    - {}
    "subscription_id": "subscription_guid"
    "tenant_id": "tenant_guid"
"resource":
  "azurerm_resource_group":
    "pythonazure_testrg_4EE2DCD8":
      "location": "northeurope"
      "name": "test"
"terraform":
  "required_providers":
    "azurerm": "~> 2.0"
Removed local_file.tfCode_yaml
Successfully removed 1 resource instance(s).

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "local" (hashicorp/local) 1.4.0...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.local: version = "~> 1.4"

Terraform has been successfully initialized!
local_file.tfCode_json: Creating...
local_file.tfCode_json: Creation complete after 0s [id=5fd727326df656683eb44aea3fdc17a6a06c6e20]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

decoded_json = {"//":{"metadata":{"stackName":"python-azure","version":"0.0.12"}},"provider":{"azurerm":[{"features":[{}],"subscription_id":"subscription_guid","tenant_id":"tenant_guid"}]},"resource":{"azurerm_resource_group":{"pythonazure_testrg_4EE2DCD8":{"location":"northeurope","name":"test"}}},"terraform":{"required_providers":{"azurerm":"~\u003e 2.0"}}}
{
    "//": {
        "metadata": {
            "stackName": "python-azure",
            "version": "0.0.12"
        }
    },
    "provider": {
        "azurerm": [
            {
                "features": [
                    {}
                ],
                "subscription_id": "subscription_guid",
                "tenant_id": "tenant_guid"
            }
        ]
    },
    "resource": {
        "azurerm_resource_group": {
            "pythonazure_testrg_4EE2DCD8": {
                "location": "northeurope",
                "name": "test"
            }
        }
    },
    "terraform": {
        "required_providers": {
            "azurerm": "~> 2.0"
        }
    }
}

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "azurerm" (hashicorp/azurerm) 2.20.0...

Terraform has been successfully initialized!
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

Error: Error building AzureRM Client: Error retrieving the Profile from the Azure CLI: Subscription "subscription_guid"
```

## Essentially for me this would have mainly two use cases:
- Let users to just edit the YAML with their settings and then use it programatically
- YAML is very effective for locals as I can quickly dump local variables into YAML format for reference, ask users to fill in only specified fields.

If I could produce YAML directly from cdktf it would be great as I wouldn't have to use terraform multiple times for conversion

YAML used for modules:

```hcl
locals {
  environment = var.environment
  vars_aks    = local.vars_aks_raw[local.environment]
  vars_aks_raw = {
    td = yamldecode(file("${path.module}/aks_settings.${local.environment}.yml"))
  }
}
```

```yaml
#######################################################################################################################
default_node_pool:
  availability_zones:
    - 1
    - 2
    - 3
  enable_auto_scaling: true
  enable_node_public_ip: false
  max_count: 10
  max_pods: 100
  min_count: 1
  name: nodepool1
  node_count: 2
  node_labels: {}
  node_taints: []
  os_disk_size_gb: 100
  type: VirtualMachineScaleSets
  vm_size: Standard_DS2_v2
  vnet_subnet_id: "/subscriptions/<>\
                   /resourceGroups/<>\
                   /providers/Microsoft.Network/virtualNetworks/<>\
                   /subnets/<>"

#######################################################################################################################
aks_kubernetes_info:
  aks_cluster_name: <>
  aks_cluster_resource_group: <>
  aks_kubernetes_version: latest
  aks_load_balancer_sku: Standard
  outbound_type: userDefinedRouting
  private_cluster_enabled: true
  rbac_enabled: true
#######################################################################################################################
aks_log_analytics_details:
  log_analytics_workspace_id: "/subscriptions/<>\
                               /resourcegroups/<>\
                               /providers/microsoft.operationalinsights/workspaces/<>"
  oms_agent_enabled: true

#######################################################################################################################
aks_node_linux_profile:
  admin_username: azureuser
  enabled: false
  ssh_key_data: ssh-rsa xxxxxxxx

#######################################################################################################################
additional_node_pools: {}
```
