### ISSUE TITLE
Yarn  pnp support

### ISSUE THREAD

**Issue by gkaskonas** [hashicorp/terraform-cdk#3149]
### Expected Behavior

Should install using pnp and work

### Actual Behavior

```
Error: @cdktf/provider-generator tried to access glob, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

Tried adding dependencies to packageExtensions but got stuck with the prebuilt binary

```
packageExtensions:
  "@cdktf/provider-generator@*":
    dependencies:
      glob: "10.3.10"
  "@cdktf/hcl2cdk@*":
    dependencies:
      codemaker: "1.89.0"
      cdktf: "0.18.0"
  "cdktf-cli@*":
    dependencies:
      "@cdktf/node-pty-prebuilt-multiarc": "*"
```

`➤ YN0035: │ @cdktf/node-pty-prebuilt-multiarc@npm:*: Package not found`

### Steps to Reproduce

1. Create a new cdktf project
2. install dependencies
3. run cdktf diff

### Versions

language: typescript
cdktf-cli: 0.18.0
node: v20.5.0
cdktf: null
constructs: null
jsii: null
terraform: 1.3.7
arch: arm64
os: darwin 22.6.0

### Possible Solutions

Fix package.json dependencies

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment
