### ISSUE TITLE
Add Dependabot Configuration 

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#362]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We could configure Dependabot to update:

- Github Actions
- NPM Packages

I'm not sure how useful the github actions part is, that's something to investigate. For the NPM package ecosystem, I think it would be quite handy to automatically upgrade non-critical packages.

Critical packages I think we'd want to handle manually (taken from the [AWS CDK config](https://github.com/aws/aws-cdk/blob/443948164e09aaa81c094c013b32aa1f67b69570/.dependabot/config.yml)):

```yaml
      - match:
          dependency_name: "jsii*"
      - match:
          dependency_name: "@jsii/*"
      - match:
          dependency_name: "codemaker"
```

### References

There was an initial Pull Request with a few references https://github.com/hashicorp/terraform-cdk/pull/316

- https://docs.github.com/en/github/administering-a-repository/customizing-dependency-updates
- https://github.com/aws/aws-cdk/blob/443948164e09aaa81c094c013b32aa1f67b69570/.dependabot/config.yml
